import { ApiError } from "../class/api.error";
import { cloudService } from "../config/cloudinary";
import { BrandDto } from "../contract/brand.dto";
import { CreateBrand, UpdateBrand } from "../schemas/brand.schema";
import { BrandRepo, brandRepo } from "../repo/brand.repo";
import { QueryString } from "../schemas/standred.schema";
import fs from "fs";

export class BrandService {
  constructor(private readonly brandRepo: BrandRepo) {}

  async create(data: CreateBrand, file?: Express.Multer.File) {
    const defaultImage = { url: "", publicId: "" };
    
    // Prepare initial DTO
    // Slug handled by model middleware
    let brandData: BrandDto = {
      ...data,
      slug: "", // Will be generated by mongoose pre-save hook
      image: data.image || defaultImage,
      status: data.status || "active", // fallback just in case
    };

    if (file) {
      const { url, publicId } = await cloudService.uploadSinglePhoto(
        file.path,
        "brands",
      );
      fs.unlinkSync(file.path);
      brandData.image = { url, publicId };
    }
    
    const brand = await this.brandRepo.create(brandData);
    return { brand };
  }
  async update(id: string, data: UpdateBrand, file?: Express.Multer.File) {
    const existBrand = await this.brandRepo.findById(id);
    if (!existBrand) throw new ApiError("Brand not found", 404);
    
    let image = existBrand.image;
    if (file) {
      const { url, publicId } = await cloudService.uploadSinglePhoto(
        file.path,
        "brands",
      );
      fs.unlinkSync(file.path);
      image = { url, publicId };
      if (existBrand.image?.publicId) {
        await cloudService.deletePhoto(existBrand.image.publicId);
      }
    }
    
    // Construct the object to update
    // Slug handled by model middleware on name change
    const updateData: Partial<BrandDto> = {
      ...data,
      image,
    };
    
    const brand = await this.brandRepo.update(id, updateData as any);
    if (!brand) throw new ApiError("Brand not found", 404);
    return { brand };
  }
  async softDelete(id: string) {
    const brand = await this.brandRepo.softDelete(id);
    if (!brand) throw new ApiError("Brand not found", 404);
    return { brand };
  }
  async findById(id: string) {
    const brand = await this.brandRepo.findById(id);
    if (!brand) throw new ApiError("Brand not found", 404);
    return { brand };
  }
  async findAll(query: QueryString) {
    const brands = await this.brandRepo.findAll(query);
    return { brands };
  }
}
export const brandService = new BrandService(brandRepo);
